fix(http-utils): fix for Axios for service worker environment
In service worker environments (eg Cloudflare workers), XMLHttpRequest used by Axios is deprecated.
When using the @taquito/http-utils package in such an environment, the following error occurs:
TypeError: adapter is not a function. Made a fix to use @vespaiach/axios-fetch-adapter when not in a
nodejs environment.

fix #2025